apiVersion: apps/v1
kind: Deployment
metadata:
  name: sitequestaoeventhub 
 labels:
    app: sitequestaoeventhub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sitequestaoeventhub
  template:
    metadata:
      labels:
        app: sitequestaoeventhub
    spec:
      containers:
      - name: sitequestaoeventhub
        image: acrdemoptc.azurecr.io/sitequestaoeventhub:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: sitequestaoeventhub
spec:
  selector:
    app: sitequestaoeventhub
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer